---
name: "PikPak"
guid: "513FD7F0-2F49-44AA-85A1-FBF328469F66"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "PikPak plugin for jellyfin"
description: >
  PikPak plugin for jellyfin.
category: "General"
owner: "ykxVK8yL5L"
artifacts:
- "Jellyfin.Plugin.PikPak.dll"
changelog: >
  changelog
